name: Mirror Azure DevOps → GitHub

permissions:
  contents: write

# Puedes disparar manualmente o por cron
on:
  workflow_dispatch:
  schedule:
    - cron: '*/60 * * * *'  # cada 60 minutos

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar mirror de Azure DevOps
        run: |
          git clone --mirror \
            https://${{ secrets.AZURE_DEVOPS_PAT }}@dev.azure.com/certificacioneslabs/Store%20Intelligence/_git/Store%20Intelligence \
            repo-mirror
      - name: Empujar mirror a GitHub
        working-directory: repo-mirror
        run: |
          git remote set-url --push origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/gquintal/Portafolio.git
          git push --mirror
